spring:
  application:
    name: member-service-provider

  config:
    import: aws-secretsmanager:flexshare-service-config

  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        instance-profile: true

server:
  port: 10001
  servlet:
    session:
      cookie:
        secure: false
        same-site: none
