name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - flexShareServer

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ secrets.AWS_EC2_SSH_KEY_SPRINGBOOT }}
      EC2_HOST: ${{ secrets.AWS_EC2_HOST_SPRINGBOOT }}
      EC2_USER: ${{ secrets.AWS_EC2_USER_SPRINGBOOT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build JAR
      run: mvn -B -DskipTests clean package

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/aws.pem
        chmod 600 ~/.ssh/aws.pem
        ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

    - name: Copy JAR to EC2
      run: |
        scp -i ~/.ssh/aws.pem -o StrictHostKeyChecking=no target/*.jar $EC2_USER@$EC2_HOST:/home/ubuntu/app/member-service.jar

    - name: Restart Spring Boot service
      run: |
        ssh -i ~/.ssh/aws.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
          echo "Killing old Spring Boot process..."
          pkill -f 'java -jar' || echo "No process found"

          echo "Starting new Spring Boot process..."
          nohup java -jar /home/ubuntu/app/member-service.jar > /home/ubuntu/app/app.log 2>&1 &
        EOF
